### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by AntouanK** [geokapp/arc-variants#1]
Having a small dependency issue.
(  using Antergos )
```
-> % ./arc-variants -i=green-hidpi
Cleaning...
Done.
Checking dependencies...
Checking sed...ok
Checking python...ok
Checking autoconf...ok
Checking automake...ok
Checking pkgconfig...failed.
Checking git...ok
Checking inkscape...ok
Checking optipng...ok
Install the missing dependencies and try again.
antouank@i7 [18:08:19] [~/_REPOS_/arc-variants] [master]
-> % yaourt -Ss pkgconfig
core/pkg-config 0.29.1-2 (base-devel) [installed]
```

`pkgconfig` is installed, but it fails on configure.

**Comment by geokapp** [comment]
The last [commit](https://github.com/geokapp/arc-variants/commit/4b8b5629493bdd1c962c110af22b5ffec5e6bbc5) should fix it. Can you try it and report back? :)

**Comment by AntouanK** [comment]
`pkg-config` fixed. :+1: 

Fails on `nvm` now.
I already have node 7.3.0. ( why do you need `nvm` )
Tried to get `nvm` from AUR but it still fails.

**Comment by geokapp** [comment]
This is a build dependency of the original Arc-theme. See [here](https://github.com/horst3180/arc-theme/blob/master/HACKING.md).

**Comment by AntouanK** [comment]
Got `nvm`, check is still failing though.
I have latest node installed using `nvm`.

I can see `hash: no such command: nvm` gives `no such command`.
but `nvm` runs fine.
And `which nvm` returns... a weird script!

**Comment by geokapp** [comment]
OK, I removed the `nvm` dependency completely. It seems that the Arc theme can be built without it. Can you try once more?

**Comment by AntouanK** [comment]
that's what I did. 
It's still building...

**Comment by geokapp** [comment]
You can also use the `-v=22` flag to build for the last GTK3 version in order to reduce the build time. ;)

**Comment by AntouanK** [comment]
Can I also build only for xfwm? ( that's what I need for XFCE I suppose )

**Comment by geokapp** [comment]
Unfortunately, there isn't such an option yet. The xfwm is only used for the window frames. You still need the gtk2 part for the contents and the gtk3 part for compatibility with gtk3 apps (e.g., evince, gedit).

**Comment by AntouanK** [comment]
It's alright.
It worked fine btw! Thanks.
I'll try to build again with a custom color.

**Comment by AntouanK** [comment]
The custom one didn't work out very well... 
Is this correct for #192B51?
`./arc-variants -i=darkblue-hidpi:192B51 -v=22`

I get a weird theme...

**Comment by geokapp** [comment]
Yep this is correct. On my machine this command produces a blue variant which is lighter than #192b51 bur darker than the default blue. The problem is that currently the tool uses only the hue value (or the saturation if the hue is zero) of the user provided color and keeps the lightness and saturation of the build-in colors. This is done in order to keep the original color tones.

**Comment by AntouanK** [comment]
@geokapp 
When I build using custom colors, I get those error messages
```
SyntaxError: invalid syntax
  File ".../arc-variants/internal/scripts/map_color.py", line 48
    print "%s%s%s" % (format(rgbresult[0], 'x'), format(rgbresult[1], 'x'), format(rgbresult[2], 'x'))
```


command:
`./arc-variants -i=darkblue-hidpi:#1C212C -v=22`

**Comment by AntouanK** [comment]
I've done also a build without the `#`

Here's the result ( `blue` is a variant and it works fine, `darkblue` is the one I built and it doesn't :) )
[screencapture.zip](https://github.com/geokapp/arc-variants/files/693326/screencapture.zip)

**Comment by geokapp** [comment]
Probably it was a compatibility issue with python 3 and up. This [commit](https://github.com/geokapp/arc-variants/commit/88f91b1a9b7eb3a8135b62e41e89245a46ca0b80) should fix it.

**Comment by AntouanK** [comment]
That seems to work. ( although I still get some "random" secondary colours )
Thanks.
